apply plugin: 'com.android.library'
apply plugin: 'expo-module-gradle-plugin'

group = 'expo.modules.smsforwarder'
version = '1.0.0'

android {
  namespace 'expo.modules.smsforwarder'
  defaultConfig { versionCode 1; versionName '1.0.0' }
}

dependencies {
  testImplementation 'junit:junit:4.13.2'
}
